### ISSUE TITLE
Set up MongoDB server

### ISSUE THREAD

**Issue by alexpclarke** [AgileAppstate/discus-whole-class-team#1]

**Comment by fenwickjb** [comment]
It does not appear that mongod service is currently installed on the Pi. Will inquire with infrastructure team if this is possible.

**Comment by fenwickjb** [comment]
So, architecturally, will the web/cli/util subsystems all be required to interface with this db? If so, we will need to involve those other teams in the decision.

**Comment by hessorr** [comment]
resource for using mongoDb with Python: 
https://pymongo.readthedocs.io/en/stable/tutorial.html

**Comment by hessorr** [comment]
Had Tim install pymongo on the pi
