### ISSUE TITLE
Image_insert should handle non-existent filepaths

### ISSUE THREAD

**Issue by phdavis1027** [AgileAppstate/discus-whole-class-team#86]
The current implementation of utils.images.image_insert finds images in the filesystem like this:

```
    with open(path, 'rb') as f:
        contents = f.read()

```

On the CLI side, I handle the FileNotFoundError, but this is really the province of the utils module.

**Comment by cosmicboots** [comment]
Errors should probably be handled at the top level. 
This would let the error be surfaced to the user in a more ergonomic way.
