### ISSUE TITLE
`api.views.cursor_to_json` only returns object keys

### ISSUE THREAD

**Issue by phdavis1027** [AgileAppstate/discus-whole-class-team#96]
**What I did:**

Here's the code:
```
formatted_json = views.cursor_to_json(fetched) 
click.echo(formatted_json)
```

**What I expected was:**

A json object representing the list of records fetched from Mongo.

**What I got was:**

This:

```
[
"id",
"name",
"playlist",
"mode", 
"recurring_info",
"start_date",
"end_date",
"time_occurances",
"date_created"
]
```

Which is just the keys from the actual object.

**Comment by cosmicboots** [comment]
This seems to be working now. Reopen if the issue persists.
